#pragma config(Sensor, in1,    light,          sensorReflection)
#pragma config(Sensor, dgtl1,  encoder,        sensorQuadEncoder)
#pragma config(Motor,  port2,           LM,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           RM,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           ARM,           tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port5,           ARM2,          tmotorVex269_MC29, openLoop, reversed)
#pragma config(UART_Usage, UART1, uartUserControl, baudRate115200, IOPins, None, None)
#pragma config(UART_Usage, UART2, uartUserControl, baudRate4800, IOPins, None, None)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "BNSlib_HC05.h"

/**
* Turns left for the given amount of time,
* then turns right for the given amount of time
*/
void jiggle(int seconds){
	motor[LM] = 30;
  	motor[RM] = 30;
  	wait(1);
	motor[LM] = -30;
	motor[RM] = -30;
}

task main()
{
	clearDebugStream();
	//send dummy data
	char buf[9];
	buf[0] = 't';
	bnsSerialSend(UART1, buf, 9);
	writeDebugStream("Sent dummy data\n");

	
	//jiggle for visual confirmation
  //jiggle(1);	
	
	
	//send actual light data
	short val = SensorValue[light];
	sendChar(UART1,val);
	writeDebugStream("Sent light data\n");

}
