#pragma config(Sensor, in1,    light,          sensorReflection)
#pragma config(UART_Usage, UART1, uartUserControl, baudRate115200, IOPins, None, None)
#pragma config(UART_Usage, UART2, uartUserControl, baudRate4800, IOPins, None, None)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "BNSlib_HC05.h"
task main()
{
	//int x = 10;
	char buf[9];
	buf[0] = 't';
	//sprintf(buf, "%d", x);
	bnsSerialSend(UART1, buf, 9);
	writeDebugStream("Sent\n");

	while(true){
		wait(1);
		writeDebugStream("Sending light data\n");

		char buf[9];
		int val = SensorValue[light];
		int value = 123;
		int count = 0;
		while (val > 0) {

 			int digit = val % 10;
		  value /= 10;
		  buf[count] = digit;
		  count++;
		}
		bnsSerialSend(UART1, buf, 9);
		writeDebugStream("Sent\n");

	}
}
